export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER = 'CREATE_USER';
export const LOAN_APPLICATION = 'LOAN_APPLICATION';
export const LOAN_APPLICATION_SUCCESS = 'LOAN_APPLICATION_SUCCESS';
export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const GET_APPLICATION_STATUS = 'GET_APPLICATION_STATUS';
export const GET_APPLICATION_STATUS_SUCCESS = 'GET_APPLICATION_STATUS_SUCCESS';
